sudo: false
language: scala
dist: xenial

scala:
  - 2.13.2
  - 2.12.10

jdk:
  - openjdk8

before_install:
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.6.3 --install --fuzzy
  - gem update --system
  - gem install bundler
  - bundle install

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheckAll
  - test $TRAVIS_SCALA_VERSION == "2.13.2" && sbt ++$TRAVIS_SCALA_VERSION "scalafixAll --check"
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues
  - sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "TimWSpence/cats-stm" && sbt ++$TRAVIS_SCALA_VERSION publish
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "TimWSpence/cats-stm" && test $TRAVIS_SCALA_VERSION == "2.13.1" && sbt docs/publishMicrosite

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt
