name: Cats STM
baseurl: /cats-stm
description: Software Transactional Memory for Cats Effect
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.4.1-SNAPSHOT
org: timwspence
markdown: kramdown
